version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - db
    networks:
      - app-php

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8891:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-php

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-security}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app-php

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - app-php

networks:
  app-php:
    driver: bridge
